[project]
name = "mcp-cotutor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.11.0",
    "uvicorn>=0.35.0",
]
